---
- name: Install apache2
  hosts: server
  become: true

  tasks:
    - name: Install apache2 and dependencies
      package:
        name:
          - apache2
          - libapache2-mod-php
        update_cache: true
        cache_valid_time: 3600

    - name: Copy apache2 configuration files
      copy:
        src: /vagrant/config/apache2/certs
        dest: /etc/apache2/
        remote_src: yes
        force: yes

    - name: Copy apache2 configuration files
      copy:
        src: /vagrant/config/apache2/.htpasswd
        dest: /etc/apache2/.htpasswd
        remote_src: yes

    - name: Copy apache2 configuration files
      copy:
        src: /vagrant/config/apache2/apache2.conf
        dest: /etc/apache2/apache2.conf
        remote_src: yes

    - name: Copy apache2 configuration files
      copy:
        src: /vagrant/config/apache2/sites-available/pumukydev.conf
        dest: /etc/apache2/sites-available/pumukydev.conf
        remote_src: yes

    - name: Copy htdocs files
      copy:
        src: "/vagrant/htdocs/"
        dest: "/var/www/htdocs/"
        remote_src: yes

    - name: Enable apache2 site configuration
      command:
        cmd: a2ensite pumukydev.conf
        creates: /etc/apache2/sites-enabled/pumukydev.conf

    - name: Enable Apache2 modules
      command:
        cmd: a2enmod "{{ item }}"
      loop:
        - ssl
        - proxy
        - proxy_http
        - headers

    - name: Restart Apache2 service
      service:
        name: apache2
        state: restarted
