---
- name: Install basic packages
  hosts: server
  become: true

  tasks:
    - name: Install some packages
      package:
        name:
          # Networking tools
          - curl
          - wget
          - apt-transport-https

          # PHP packages
          - php

          # Encryption tools
          - gnupg
          - gnupg2
          - software-properties-common

          # JSON tools
          - jq
        update_cache: true
        cache_valid_time: 3600
