---
- name: Dynamic DNS configuration
  hosts: server
  become: true

  tasks:
    - name: Copy dynamic DNS scripts
      copy:
        src: "/vagrant/config/dynamic-dns/get_url/"
        dest: "/opt/dynamic-dns/"
        remote_src: yes

    - name: Make the dyndns script executable
      file:
        path: "/opt/dynamic-dns/dyndns.sh"
        mode: '0755'

    - name: Copy cron job for Dynamic DNS update
      copy:
        src: "/vagrant/config/dynamic-dns/dyndns-cronjob"
        dest: "/etc/cron.d/dyndns"
        remote_src: yes
